dubbo :
  protocol:
    prot : -1
    name  : dubbo
  application:
    name : hello-world-app
  registry:
    address : zookeeper://127.0.0.1:2181
  packageName : com.ibigsea.dubbo_consume.reference
  
server :
  port : 8085